# WARNING! 
#
# This file includes the secrets required to setup and configure the 
# TEST cluster.  This must always be encrypted at rest and also when 
# committed to Git.  You can use the following commands to view or edit
# this file using the [tarukino-git] encryption password:
#
#		neon file view secrets.yaml tarukino-git
#		neon file edit secrets.yaml tarukino-git

