name: office-large
datacenter: fremont
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: false
hosting:
  environment: hyperv-local
  vmDriveFolder: C:\\VM
network:
  premiseSubnet: 10.50.0.0/16
  nodesSubnet: 10.50.0.0/16
nodeOptions:
  upgrade: none
  passwordLength: 20
nodes:
  master-0:
    role: master
    privateAddress: 10.50.0.30
  master-1:
    role: master
    privateAddress: 10.50.0.31
  master-2:
    role: master
    privateAddress: 10.50.0.32
  worker-0:
    role: worker
    privateAddress: 10.50.0.40
  worker-1:
    role: worker
    privateAddress: 10.50.0.41
  worker-2:
    role: worker
    privateAddress: 10.50.0.42
