name: office-tiny
datacenter: fremont
environment: development
timeSources:
- pool.ntp.org
allowUnitTesting: true
kubernetes:
  allowPodsOnMasters: true
hosting:
  environment: hyperv-local
  vmDriveFolder: C:\\VM
network:
  premiseSubnet: 10.50.0.0/16
  nodesSubnet: 10.50.0.0/16
nodeOptions:
  upgrade: none
  passwordLength: 20
Nodes:
  master-0:
    role: master
    privateAddress: 10.50.0.30
